// Code generated by "stringer -type=AddAttrDataType addattrdatatype.go"; DO NOT EDIT.

package mayaascii

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AddAttrDataTypeInvalid-0]
	_ = x[AddAttrDataTypeInt32Array-1]
	_ = x[AddAttrDataTypeDouble2-2]
	_ = x[AddAttrDataTypeDouble3-3]
	_ = x[AddAttrDataTypeDoubleArray-4]
	_ = x[AddAttrDataTypeFloat2-5]
	_ = x[AddAttrDataTypeFloat3-6]
	_ = x[AddAttrDataTypeFloatArray-7]
	_ = x[AddAttrDataTypeLattice-8]
	_ = x[AddAttrDataTypeLong2-9]
	_ = x[AddAttrDataTypeLong3-10]
	_ = x[AddAttrDataTypeMatrix-11]
	_ = x[AddAttrDataTypeMesh-12]
	_ = x[AddAttrDataTypeNurbsCurve-13]
	_ = x[AddAttrDataTypeNurbsSurface-14]
	_ = x[AddAttrDataTypePointArray-15]
	_ = x[AddAttrDataTypeReflectanceRGB-16]
	_ = x[AddAttrDataTypeShort2-17]
	_ = x[AddAttrDataTypeShort3-18]
	_ = x[AddAttrDataTypeSpectrumRGB-19]
	_ = x[AddAttrDataTypeString-20]
	_ = x[AddAttrDataTypeStringArray-21]
	_ = x[AddAttrDataTypeVectorArray-22]
}

const _AddAttrDataType_name = "AddAttrDataTypeInvalidAddAttrDataTypeInt32ArrayAddAttrDataTypeDouble2AddAttrDataTypeDouble3AddAttrDataTypeDoubleArrayAddAttrDataTypeFloat2AddAttrDataTypeFloat3AddAttrDataTypeFloatArrayAddAttrDataTypeLatticeAddAttrDataTypeLong2AddAttrDataTypeLong3AddAttrDataTypeMatrixAddAttrDataTypeMeshAddAttrDataTypeNurbsCurveAddAttrDataTypeNurbsSurfaceAddAttrDataTypePointArrayAddAttrDataTypeReflectanceRGBAddAttrDataTypeShort2AddAttrDataTypeShort3AddAttrDataTypeSpectrumRGBAddAttrDataTypeStringAddAttrDataTypeStringArrayAddAttrDataTypeVectorArray"

var _AddAttrDataType_index = [...]uint16{0, 22, 47, 69, 91, 117, 138, 159, 184, 206, 226, 246, 267, 286, 311, 338, 363, 392, 413, 434, 460, 481, 507, 533}

func (i AddAttrDataType) String() string {
	if i < 0 || i >= AddAttrDataType(len(_AddAttrDataType_index)-1) {
		return "AddAttrDataType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AddAttrDataType_name[_AddAttrDataType_index[i]:_AddAttrDataType_index[i+1]]
}
