// Code generated by "stringer -type=AddAttrAttributeType addattrattributetype.go"; DO NOT EDIT.

package mayaascii

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AddAttrAttributeTypeInvalid-0]
	_ = x[AddAttrAttributeTypeBool-1]
	_ = x[AddAttrAttributeTypeByte-2]
	_ = x[AddAttrAttributeTypeChar-3]
	_ = x[AddAttrAttributeTypeCompound-4]
	_ = x[AddAttrAttributeTypeDouble-5]
	_ = x[AddAttrAttributeTypeDouble2-6]
	_ = x[AddAttrAttributeTypeDouble3-7]
	_ = x[AddAttrAttributeTypeDoubleAngle-8]
	_ = x[AddAttrAttributeTypeDoubleLinear-9]
	_ = x[AddAttrAttributeTypeEnum-10]
	_ = x[AddAttrAttributeTypeFloat-11]
	_ = x[AddAttrAttributeTypeFloat2-12]
	_ = x[AddAttrAttributeTypeFloat3-13]
	_ = x[AddAttrAttributeTypeFltMatrix-14]
	_ = x[AddAttrAttributeTypeLong-15]
	_ = x[AddAttrAttributeTypeLong2-16]
	_ = x[AddAttrAttributeTypeLong3-17]
	_ = x[AddAttrAttributeTypeMessage-18]
	_ = x[AddAttrAttributeTypeReflectance-19]
	_ = x[AddAttrAttributeTypeShort-20]
	_ = x[AddAttrAttributeTypeShort2-21]
	_ = x[AddAttrAttributeTypeShort3-22]
	_ = x[AddAttrAttributeTypeSpectrum-23]
	_ = x[AddAttrAttributeTypeTime-24]
}

const _AddAttrAttributeType_name = "AddAttrAttributeTypeInvalidAddAttrAttributeTypeBoolAddAttrAttributeTypeByteAddAttrAttributeTypeCharAddAttrAttributeTypeCompoundAddAttrAttributeTypeDoubleAddAttrAttributeTypeDouble2AddAttrAttributeTypeDouble3AddAttrAttributeTypeDoubleAngleAddAttrAttributeTypeDoubleLinearAddAttrAttributeTypeEnumAddAttrAttributeTypeFloatAddAttrAttributeTypeFloat2AddAttrAttributeTypeFloat3AddAttrAttributeTypeFltMatrixAddAttrAttributeTypeLongAddAttrAttributeTypeLong2AddAttrAttributeTypeLong3AddAttrAttributeTypeMessageAddAttrAttributeTypeReflectanceAddAttrAttributeTypeShortAddAttrAttributeTypeShort2AddAttrAttributeTypeShort3AddAttrAttributeTypeSpectrumAddAttrAttributeTypeTime"

var _AddAttrAttributeType_index = [...]uint16{0, 27, 51, 75, 99, 127, 153, 180, 207, 238, 270, 294, 319, 345, 371, 400, 424, 449, 474, 501, 532, 557, 583, 609, 637, 661}

func (i AddAttrAttributeType) String() string {
	if i < 0 || i >= AddAttrAttributeType(len(_AddAttrAttributeType_index)-1) {
		return "AddAttrAttributeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AddAttrAttributeType_name[_AddAttrAttributeType_index[i]:_AddAttrAttributeType_index[i+1]]
}
