// Code generated by "stringer -type=AttrType attrtype.go"; DO NOT EDIT.

package mayaascii

import "strconv"

const _AttrType_name = "TypeInvalidTypeBoolTypeIntTypeDoubleTypeShort2TypeShort3TypeLong2TypeLong3TypeInt32ArrayTypeFloat2TypeFloat3TypeDouble2TypeDouble3TypeDoubleArrayTypeMatrixTypeMatrixXformTypePointArrayTypeVectorArrayTypeStringTypeStringArrayTypeSphereTypeConeTypeReflectanceRGBTypeSpectrumRGBTypeComponentListTypeAttributeAliasTypeNurbsCurveTypeNurbsSurfaceTypeNurbsTrimfaceTypePolyFacesTypeDataPolyComponentTypeMeshTypeLattice"

var _AttrType_index = [...]uint16{0, 11, 19, 26, 36, 46, 56, 65, 74, 88, 98, 108, 119, 130, 145, 155, 170, 184, 199, 209, 224, 234, 242, 260, 275, 292, 310, 324, 340, 357, 370, 391, 399, 410}

func (i AttrType) String() string {
	if i < 0 || i >= AttrType(len(_AttrType_index)-1) {
		return "AttrType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AttrType_name[_AttrType_index[i]:_AttrType_index[i+1]]
}
