// Code generated by "stringer -type=AttrType attrtype.go"; DO NOT EDIT.

package mayaascii

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TypeInvalid-0]
	_ = x[TypeBool-1]
	_ = x[TypeInt-2]
	_ = x[TypeDouble-3]
	_ = x[TypeShort2-4]
	_ = x[TypeShort3-5]
	_ = x[TypeLong2-6]
	_ = x[TypeLong3-7]
	_ = x[TypeInt32Array-8]
	_ = x[TypeFloat2-9]
	_ = x[TypeFloat3-10]
	_ = x[TypeDouble2-11]
	_ = x[TypeDouble3-12]
	_ = x[TypeDoubleArray-13]
	_ = x[TypeMatrix-14]
	_ = x[TypeMatrixXform-15]
	_ = x[TypePointArray-16]
	_ = x[TypeVectorArray-17]
	_ = x[TypeString-18]
	_ = x[TypeStringArray-19]
	_ = x[TypeSphere-20]
	_ = x[TypeCone-21]
	_ = x[TypeReflectanceRGB-22]
	_ = x[TypeSpectrumRGB-23]
	_ = x[TypeComponentList-24]
	_ = x[TypeAttributeAlias-25]
	_ = x[TypeNurbsCurve-26]
	_ = x[TypeNurbsSurface-27]
	_ = x[TypeNurbsTrimface-28]
	_ = x[TypePolyFaces-29]
	_ = x[TypeDataPolyComponent-30]
	_ = x[TypeDataReferenceEdits-31]
	_ = x[TypeMesh-32]
	_ = x[TypeLattice-33]
}

const _AttrType_name = "TypeInvalidTypeBoolTypeIntTypeDoubleTypeShort2TypeShort3TypeLong2TypeLong3TypeInt32ArrayTypeFloat2TypeFloat3TypeDouble2TypeDouble3TypeDoubleArrayTypeMatrixTypeMatrixXformTypePointArrayTypeVectorArrayTypeStringTypeStringArrayTypeSphereTypeConeTypeReflectanceRGBTypeSpectrumRGBTypeComponentListTypeAttributeAliasTypeNurbsCurveTypeNurbsSurfaceTypeNurbsTrimfaceTypePolyFacesTypeDataPolyComponentTypeDataReferenceEditsTypeMeshTypeLattice"

var _AttrType_index = [...]uint16{0, 11, 19, 26, 36, 46, 56, 65, 74, 88, 98, 108, 119, 130, 145, 155, 170, 184, 199, 209, 224, 234, 242, 260, 275, 292, 310, 324, 340, 357, 370, 391, 413, 421, 432}

func (i AttrType) String() string {
	if i < 0 || i >= AttrType(len(_AttrType_index)-1) {
		return "AttrType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AttrType_name[_AttrType_index[i]:_AttrType_index[i+1]]
}
